/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState,useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import cubeModel from "../assets/cubeModel.glb"
import * as THREE from "three"
import url from "../assets/kda.mp4"
import { useFrame } from "@react-three/fiber";
import GSAP from "gsap"

const Cube = (props)=> {
  const [lerp, setLerp] = useState({
    current : 0,
    target : 0,
    ease : 0.1
  });
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(cubeModel);
  const {actions,names,mixer} = useAnimations(animations,group)
  // console.log(actions);
  useEffect(() => {
    actions[names[0]].play();
  }, [mixer]);

  const [video] = useState(()=>{
    const video = document.createElement('video');
    video.src = url;
    video.loop = true;
    video.muted = true;
    video.autoplay = true;
    return video;
  })
  const onMouseMove = (e) => {
    const rotation = ((e.clientX - window.innerWidth / 2) * 2) / window.innerWidth;
    setLerp({
      ...lerp,
      target : rotation,
    });
    const current = GSAP.utils.interpolate(
      lerp.current,
      lerp.target,
      lerp.ease
    )
    group.current.rotation.y = current;
    // console.log(lerp);

  }
  
  useEffect(() => {
    window.addEventListener('mousemove', onMouseMove);
    return () => {
      window.removeEventListener('mousemove', onMouseMove);
    };
  }, [lerp]);
  

  return (
    <group ref={group} {...props} dispose={null} >
      <group name="Scene">
        <group
          name="Cube"
          position={[0.658, 1.336, -18.759]}
          rotation={[0, 1.536, 0]}
          scale={0.969}
        >
          <mesh
            name="Cube_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.Wall}
          />
          <mesh
            name="Cube_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials["Wall Two"]}
          />
        </group>
        <group
          name="Computer"
          position={[-7.952, 6.725, -1.05]}
          rotation={[-Math.PI, 0.823, -Math.PI]}
        >
          <mesh
            name="Cube021"
            castShadow
            receiveShadow
            geometry={nodes.Cube021.geometry}
            material={materials.Computer}
          />
          <mesh
            name="Cube021_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube021_1.geometry}
            material={materials.Screen}
          >
            <meshStandardMaterial>
              <videoTexture attach="map" args={[video]} />
            </meshStandardMaterial>
          </mesh>
        </group>
        <group
          name="Shelves"
          position={[-10.168, 12.059, 0.303]}
          rotation={[-Math.PI, 0.823, -Math.PI]}
        >
          <mesh
            name="Cylinder010"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010.geometry}
            material={materials.Material}
          />
          <mesh
            name="Cylinder010_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_1.geometry}
            material={materials.lamps}
          />
          <mesh
            name="Cylinder010_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_2.geometry}
            material={materials.Book}
          />
          <mesh
            name="Cylinder010_3"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_3.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cylinder010_4"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_4.geometry}
            material={materials.book7}
          />
          <mesh
            name="Cylinder010_5"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_5.geometry}
            material={materials.Book2}
          />
          <mesh
            name="Cylinder010_6"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_6.geometry}
            material={materials["Table Top.002"]}
          />
          <mesh
            name="Cylinder010_7"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_7.geometry}
            material={materials["pen 3"]}
          />
          <mesh
            name="Cylinder010_8"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_8.geometry}
            material={materials["Table Leg.002"]}
          />
          <mesh
            name="Cylinder010_9"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_9.geometry}
            material={materials.Profile}
          />
          <mesh
            name="Cylinder010_10"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_10.geometry}
            material={materials["profile pic"]}
          />
        </group>
        <group
          name="Mini_Floor"
          position={[-5.441, -0.82, 13.613]}
          rotation={[-Math.PI, 0.823, -Math.PI]}
        >
          <mesh
            name="Cube105"
            castShadow
            receiveShadow
            geometry={nodes.Cube105.geometry}
            material={materials.Wall}
          />
          <mesh
            name="Cube105_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube105_1.geometry}
            material={materials["Wall Two"]}
          />
        </group>
        <group
          name="Table_Stuff"
          position={[-7.615, 5.036, -0.729]}
          rotation={[-Math.PI, 0.823, -Math.PI]}
        >
          <mesh
            name="Cube114"
            castShadow
            receiveShadow
            geometry={nodes.Cube114.geometry}
            material={materials.Mini}
          />
          <mesh
            name="Cube114_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_1.geometry}
            material={materials.Pot}
          />
          <mesh
            name="Cube114_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_2.geometry}
            material={materials.Dirt}
          />
          <mesh
            name="Cube114_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_3.geometry}
            material={materials["Leaf.002"]}
          />
          <mesh
            name="Cube114_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_4.geometry}
            material={materials.Leaf}
          />
          <mesh
            name="Cube114_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_5.geometry}
            material={materials.Key}
          />
          <mesh
            name="Cube114_6"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_6.geometry}
            material={materials["Mini.001"]}
          />
          <mesh
            name="Cube114_7"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_7.geometry}
            material={materials.pen2}
          />
          <mesh
            name="Cube114_8"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_8.geometry}
            material={materials.pen1}
          />
          <mesh
            name="Cube114_9"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_9.geometry}
            material={materials["pen 3"]}
          />
          <mesh
            name="Cube114_10"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_10.geometry}
            material={materials.Book}
          />
          <mesh
            name="Cube114_11"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_11.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cube114_12"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_12.geometry}
            material={materials.Trackpad}
          />
          <mesh
            name="Cube114_13"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_13.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Cube114_14"
            castShadow
            receiveShadow
            geometry={nodes.Cube114_14.geometry}
            material={materials.drink}
          />
        </group>
        <mesh
          name="fish"
          castShadow
          receiveShadow
          geometry={nodes.fish.geometry}
          material={materials.Fish}
          position={[10.394, 5.197, 2.022]}
          rotation={[-Math.PI, 0.748, -Math.PI]}
        />
        <group
          name="Desks"
          position={[-5.602, 2.58, -0.817]}
          rotation={[-Math.PI, 0.823, -Math.PI]}
        >
          <mesh
            name="Cylinder012"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012.geometry}
            material={materials["Table Top.002"]}
          />
          <mesh
            name="Cylinder012_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012_1.geometry}
            material={materials["Table Leg.002"]}
          />
          <mesh
            name="Cylinder012_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012_2.geometry}
            material={materials["Table Leg Black.002"]}
          />
        </group>
        <group
          name="Clock"
          position={[10.621, 14.873, -0.447]}
          rotation={[-Math.PI / 2, 0, 2.319]}
        >
          <mesh
            name="Cylinder017"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder017.geometry}
            material={materials["Table Top.002"]}
          />
          <mesh
            name="Cylinder017_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder017_1.geometry}
            material={materials["Table Leg.002"]}
          />
        </group>
        <group
          name="Lamp"
          position={[-7.007, -0.455, 10.197]}
          rotation={[-Math.PI, 0.823, -Math.PI]}
        >
          <mesh
            name="Plane010"
            castShadow
            receiveShadow
            geometry={nodes.Plane010.geometry}
            material={materials.fdsa}
          />
          <mesh
            name="Plane010_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane010_1.geometry}
            material={materials.lamp}
          />
        </group>
        <group
          name="Mailbox"
          position={[-2.783, -0.681, 14.746]}
          rotation={[Math.PI / 2, 0, -2.319]}
        >
          <mesh
            name="Cylinder018"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder018.geometry}
            material={materials.Key}
          />
          <mesh
            name="Cylinder018_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder018_1.geometry}
            material={materials.book7}
          />
          <mesh
            name="Cylinder018_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder018_2.geometry}
            material={materials.Mini}
          />
        </group>
        <mesh
          name="Dirt"
          castShadow
          receiveShadow
          geometry={nodes.Dirt.geometry}
          material={materials.Dirt}
          position={[-9.131, -0.498, 11.814]}
          rotation={[-Math.PI, 0.823, -Math.PI]}
        />
        <mesh
          name="FloorThird"
          castShadow
          receiveShadow
          geometry={nodes.FloorThird.geometry}
          material={materials["seas.003"]}
          position={[-7.253, -0.498, 15.16]}
          rotation={[-Math.PI, -0.748, -Math.PI]}
        />
        <mesh
          name="FloorSecond"
          castShadow
          receiveShadow
          geometry={nodes.FloorSecond.geometry}
          material={materials.Fish}
          position={[-6.587, -0.498, 13.428]}
          rotation={[-Math.PI, -0.748, -Math.PI]}
        />
        <mesh
          name="FloorFirst"
          castShadow
          receiveShadow
          geometry={nodes.FloorFirst.geometry}
          material={materials["seas.004"]}
          position={[-4.928, -0.498, 12.76]}
          rotation={[-Math.PI, -0.748, -Math.PI]}
        />
        <group
          name="Flower1"
          position={[-9.032, -0.679, 11.597]}
          rotation={[2.453, -1.083, 1.941]}
        >
          <mesh
            name="Circle015"
            castShadow
            receiveShadow
            geometry={nodes.Circle015.geometry}
            material={materials.Book2}
          />
          <mesh
            name="Circle015_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle015_1.geometry}
            material={materials.book7}
          />
          <mesh
            name="Circle015_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle015_2.geometry}
            material={materials.Fish}
          />
        </group>
        <group
          name="Flower2"
          position={[-9.424, -0.629, 11.941]}
          rotation={[0.358, -0.554, -0.377]}
        >
          <mesh
            name="Circle016"
            castShadow
            receiveShadow
            geometry={nodes.Circle016.geometry}
            material={materials.Book2}
          />
          <mesh
            name="Circle016_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle016_1.geometry}
            material={materials.book7}
          />
          <mesh
            name="Circle016_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle016_2.geometry}
            material={materials.Fish}
          />
        </group>
        <group
          name="Floor_Items"
          position={[-2.855, -0.214, 1.604]}
          rotation={[-Math.PI, 0.823, -Math.PI]}
        >
          <mesh
            name="Cube132"
            castShadow
            receiveShadow
            geometry={nodes.Cube132.geometry}
            material={materials["Table Leg.002"]}
          />
          <mesh
            name="Cube132_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube132_1.geometry}
            material={materials["Trash Lid"]}
          />
          <mesh
            name="Cube132_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube132_2.geometry}
            material={materials["seas.003"]}
          />
          <mesh
            name="Cube132_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube132_3.geometry}
            material={materials["Table Top.002"]}
          />
        </group>
        <mesh
          name="Chair"
          castShadow
          receiveShadow
          geometry={nodes.Chair.geometry}
          material={materials["pen 3"]}
          position={[-4.151, 2.736, 2.769]}
          rotation={[0, 1.411, 0]}
        />
        <group
          name="Aquarium"
          position={[7.682, 1.61, 0.81]}
          rotation={[-Math.PI, 0.823, -Math.PI]}
        >
          <mesh
            name="Cube136"
            castShadow
            receiveShadow
            geometry={nodes.Cube136.geometry}
            material={materials["water.001"]}
            >
              <meshPhysicalMaterial
              roughness = {0}
              color= {0x549dd2}
              ior = {3}
              transmission = {1}
              opacity = {1}
              depthWrite = {false}
              depthTest = {false}
            />

          </mesh>
          <mesh
            name="Cube136_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube136_1.geometry}
            material={materials.tanke}
          />
          <mesh
            name="Cube136_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube136_2.geometry}
            material={materials.Rock}
          />
          <mesh
            name="Cube136_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube136_3.geometry}
            material={materials.seas}
          />
          <mesh
            name="Cube136_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube136_4.geometry}
            material={materials["seas.002"]}
          />
          <mesh
            name="Cube136_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube136_5.geometry}
            material={materials["seas.001"]}
          />
          <mesh
            name="Cube136_6"
            castShadow
            receiveShadow
            geometry={nodes.Cube136_6.geometry}
            material={materials.seaweed}
          />
        </group>
        <group
          name="Body"
          position={[-2.14, 10.807, -8.151]}
          rotation={[-Math.PI, 0.823, Math.PI / 2]}
        >
          <mesh
            name="Plane014"
            castShadow
            receiveShadow
            geometry={nodes.Plane014.geometry}
            material={materials.Window}
          />
          <mesh
            name="Plane014_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane014_1.geometry}
            material={materials.Wall}
          />
          <mesh
            name="Plane014_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane014_2.geometry}
            material={materials["Wall Two"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(cubeModel);

export default Cube